# Generated by Django 4.1.3 on 2022-12-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrepreneur', models.CharField(max_length=50)),
                ('pitchTitle', models.CharField(max_length=100)),
                ('pitchIdea', models.CharField(max_length=500)),
                ('askAmount', models.FloatField(default=None, null=True)),
                ('equity', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=None, null=True)),
                ('equity', models.FloatField(default=None, null=True)),
                ('comment', models.CharField(max_length=500)),
                ('pitch', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='xtank.pitch')),
            ],
        ),
    ]
